/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcd1;

import javax.swing.JFileChooser;

/**
 *
 * @author annisa
 */
public class gambarform extends javax.swing.JFrame {

    
    public ClassGambar pcd1;
    public gambarform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        mislidederajat = new javax.swing.JSlider();
        LBL_DERAJAT = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        miBuka = new javax.swing.JMenuItem();
        miSimpan = new javax.swing.JMenuItem();
        miKeluar = new javax.swing.JMenuItem();
        mnEdit = new javax.swing.JMenu();
        miGrayscale = new javax.swing.JMenuItem();
        miBiner = new javax.swing.JMenuItem();
        miDefault = new javax.swing.JMenuItem();
        miBrightness = new javax.swing.JMenuItem();
        miGeometri = new javax.swing.JMenu();
        miZoomIn = new javax.swing.JMenuItem();
        miZoomOut = new javax.swing.JMenuItem();
        miFlipVertikal = new javax.swing.JMenuItem();
        miFlipHorizontal = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mi45 = new javax.swing.JMenuItem();
        mi90 = new javax.swing.JMenuItem();
        MI180 = new javax.swing.JMenuItem();
        miFree = new javax.swing.JMenuItem();
        mirotate90right = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCD 1");

        jLabel1.setText("jLabel1");

        mislidederajat.setOrientation(javax.swing.JSlider.VERTICAL);
        mislidederajat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mislidederajatStateChanged(evt);
            }
        });

        LBL_DERAJAT.setText("jLabel2");

        mnFile.setText("File");

        miBuka.setText("Buka");
        miBuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBukaActionPerformed(evt);
            }
        });
        mnFile.add(miBuka);

        miSimpan.setText("Simpan");
        miSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSimpanActionPerformed(evt);
            }
        });
        mnFile.add(miSimpan);

        miKeluar.setText("Keluar");
        miKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKeluarActionPerformed(evt);
            }
        });
        mnFile.add(miKeluar);

        jMenuBar1.add(mnFile);

        mnEdit.setText("Edit");

        miGrayscale.setText("Grayscale");
        miGrayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGrayscaleActionPerformed(evt);
            }
        });
        mnEdit.add(miGrayscale);

        miBiner.setText("Biner");
        miBiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBinerActionPerformed(evt);
            }
        });
        mnEdit.add(miBiner);

        miDefault.setText("Default");
        miDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDefaultActionPerformed(evt);
            }
        });
        mnEdit.add(miDefault);

        miBrightness.setText(" Brightness");
        miBrightness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBrightnessActionPerformed(evt);
            }
        });
        mnEdit.add(miBrightness);

        jMenuBar1.add(mnEdit);

        miGeometri.setText("Op. Geometri");

        miZoomIn.setText("Zoom In");
        miZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZoomInActionPerformed(evt);
            }
        });
        miGeometri.add(miZoomIn);

        miZoomOut.setText("Zoom Out");
        miZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZoomOutActionPerformed(evt);
            }
        });
        miGeometri.add(miZoomOut);

        miFlipVertikal.setText("Flip Vertikal");
        miFlipVertikal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFlipVertikalActionPerformed(evt);
            }
        });
        miGeometri.add(miFlipVertikal);

        miFlipHorizontal.setText("Flip Horizontal");
        miFlipHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFlipHorizontalActionPerformed(evt);
            }
        });
        miGeometri.add(miFlipHorizontal);

        jMenuBar1.add(miGeometri);

        jMenu1.setText("Rotasi");

        mi45.setText("45'");
        jMenu1.add(mi45);

        mi90.setText("90'");
        mi90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi90ActionPerformed(evt);
            }
        });
        jMenu1.add(mi90);

        MI180.setText("180'");
        MI180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI180ActionPerformed(evt);
            }
        });
        jMenu1.add(MI180);

        miFree.setText("free rotasi");
        miFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFreeActionPerformed(evt);
            }
        });
        jMenu1.add(miFree);

        mirotate90right.setText("90'");
        mirotate90right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirotate90rightActionPerformed(evt);
            }
        });
        jMenu1.add(mirotate90right);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mislidederajat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LBL_DERAJAT)))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(LBL_DERAJAT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mislidederajat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKeluarActionPerformed
       this.dispose();
    }//GEN-LAST:event_miKeluarActionPerformed

    private void miGrayscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGrayscaleActionPerformed
        pcd1.Grayscale();
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_miGrayscaleActionPerformed

    private void miBukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBukaActionPerformed
     JFileChooser TDialog=new JFileChooser();
     if (TDialog.showOpenDialog(null)== JFileChooser.APPROVE_OPTION)
     {
         pcd1=new ClassGambar(TDialog.getSelectedFile().getAbsolutePath(),355,355);
        jLabel1.setIcon(pcd1.GetIcon());
    }

    }//GEN-LAST:event_miBukaActionPerformed

    private void miSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSimpanActionPerformed
        JFileChooser TDialog=new JFileChooser();
        if (TDialog.showOpenDialog(null)== JFileChooser.APPROVE_OPTION)
        {
            pcd1.SaveImage(TDialog.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_miSimpanActionPerformed

    private void miBinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBinerActionPerformed
        pcd1.Biner();
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_miBinerActionPerformed

    private void miDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDefaultActionPerformed
        pcd1.Default();
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_miDefaultActionPerformed

    private void miBrightnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBrightnessActionPerformed
       pcd1.Brighness();
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_miBrightnessActionPerformed

    private void miFlipHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFlipHorizontalActionPerformed
        pcd1.flipH();
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_miFlipHorizontalActionPerformed

    private void miFlipVertikalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFlipVertikalActionPerformed
        pcd1.flipV();
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_miFlipVertikalActionPerformed

    private void miZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZoomInActionPerformed
        pcd1.zoomin();
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_miZoomInActionPerformed

    private void miZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZoomOutActionPerformed
       pcd1.zoomout();
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_miZoomOutActionPerformed

    private void mi90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi90ActionPerformed
         pcd1.rotasiCitra(-90, this);
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_mi90ActionPerformed

    private void miFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFreeActionPerformed
     mislidederajat.setEnabled(true);
    }//GEN-LAST:event_miFreeActionPerformed

    private void MI180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI180ActionPerformed
       
        pcd1.rotasiCitra(180, this);
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_MI180ActionPerformed

    private void mislidederajatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mislidederajatStateChanged
        
        pcd1.rotasiCitra((double)mislidederajat.getValue(), this);
        int a = mislidederajat.getValue();
        LBL_DERAJAT.setText(Integer.toString(a));
        jLabel1.setIcon(pcd1.ScaleResultIcon);
    }//GEN-LAST:event_mislidederajatStateChanged

    private void mirotate90rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirotate90rightActionPerformed

        pcd1.rotasiCitra(90, this);
        jLabel1.setIcon(pcd1.ScaleResultIcon);
       
    }//GEN-LAST:event_mirotate90rightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gambarform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gambarform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gambarform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gambarform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gambarform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_DERAJAT;
    private javax.swing.JMenuItem MI180;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JMenuItem mi45;
    private javax.swing.JMenuItem mi90;
    private javax.swing.JMenuItem miBiner;
    private javax.swing.JMenuItem miBrightness;
    private javax.swing.JMenuItem miBuka;
    private javax.swing.JMenuItem miDefault;
    private javax.swing.JMenuItem miFlipHorizontal;
    private javax.swing.JMenuItem miFlipVertikal;
    private javax.swing.JMenuItem miFree;
    private javax.swing.JMenu miGeometri;
    private javax.swing.JMenuItem miGrayscale;
    private javax.swing.JMenuItem miKeluar;
    private javax.swing.JMenuItem miSimpan;
    private javax.swing.JMenuItem miZoomIn;
    private javax.swing.JMenuItem miZoomOut;
    private javax.swing.JMenuItem mirotate90right;
    private javax.swing.JSlider mislidederajat;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenu mnFile;
    // End of variables declaration//GEN-END:variables
}
